linters:
  disable-all: false
  disable:
    - thelper
    - varnamelen
    - tagliatelle
    - interfacer
    - wrapcheck
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
linters-settings:
  gocyclo:
    min-complexity: 11
  errcheck:
    ignore: fmt:.*,io/ioutil:^Read.*,github.com/spf13/cobra:MarkFlagRequired,github.com/spf13/viper:BindPFlag
  golint:
    min-confidence: 1.1
issues:
  exclude:
    - composite
run:
  tests: false
