// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: indexer/tx/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	tx "github.com/cosmos/cosmos-sdk/types/tx"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Pair is a struct that holds the information of a tx
type TxWithResponse struct {
	Tx         *tx.Tx            `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	TxResponse *types.TxResponse `protobuf:"bytes,2,opt,name=tx_response,json=txResponse,proto3" json:"tx_response,omitempty"`
}

func (m *TxWithResponse) Reset()         { *m = TxWithResponse{} }
func (m *TxWithResponse) String() string { return proto.CompactTextString(m) }
func (*TxWithResponse) ProtoMessage()    {}
func (*TxWithResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8509dbcaaa06dc39, []int{0}
}
func (m *TxWithResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxWithResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxWithResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TxWithResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxWithResponse.Merge(m, src)
}
func (m *TxWithResponse) XXX_Size() int {
	return m.Size()
}
func (m *TxWithResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxWithResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxWithResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TxWithResponse)(nil), "indexer.tx.v1.TxWithResponse")
}

func init() { proto.RegisterFile("indexer/tx/v1/types.proto", fileDescriptor_8509dbcaaa06dc39) }

var fileDescriptor_8509dbcaaa06dc39 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x3f, 0x4e, 0xc3, 0x30,
	0x14, 0xc6, 0xed, 0x0e, 0x08, 0xa5, 0x82, 0xa1, 0x02, 0xa9, 0xed, 0xe0, 0x22, 0xfe, 0x48, 0x2c,
	0xd8, 0x4a, 0x61, 0x62, 0x44, 0xe2, 0x02, 0x51, 0x05, 0x12, 0x4b, 0x15, 0xa7, 0x56, 0x6a, 0xa9,
	0x89, 0xa3, 0xf8, 0x25, 0x32, 0x37, 0xe8, 0xc8, 0x11, 0x3a, 0x72, 0x94, 0x8e, 0x1d, 0x19, 0x21,
	0x59, 0x38, 0x06, 0x8a, 0xed, 0x56, 0x6c, 0xef, 0xe9, 0xf7, 0x7b, 0xf9, 0xe2, 0x2f, 0x18, 0xc9,
	0x7c, 0x21, 0x8c, 0x28, 0x19, 0x18, 0x56, 0x87, 0x0c, 0xde, 0x0b, 0xa1, 0x69, 0x51, 0x2a, 0x50,
	0x83, 0x13, 0x8f, 0x28, 0x18, 0x5a, 0x87, 0xe3, 0xb3, 0x54, 0xa5, 0xca, 0x12, 0xd6, 0x4d, 0x4e,
	0x1a, 0x8f, 0x12, 0xa5, 0x33, 0xa5, 0xe7, 0x0e, 0xb8, 0xc5, 0xa3, 0xb1, 0xdb, 0xdc, 0x97, 0xb9,
	0x80, 0x38, 0x64, 0x60, 0x3c, 0xbb, 0xf2, 0x8c, 0xc7, 0x5a, 0xb0, 0x98, 0x27, 0xf2, 0xa0, 0x74,
	0x8b, 0x93, 0x2e, 0xd7, 0x38, 0x38, 0x9d, 0x99, 0x57, 0x09, 0xcb, 0x48, 0xe8, 0x42, 0xe5, 0x5a,
	0x0c, 0x6e, 0x82, 0x1e, 0x98, 0x21, 0xbe, 0xc0, 0xb7, 0xfd, 0xe9, 0x39, 0xf5, 0x71, 0xf6, 0xff,
	0xec, 0x35, 0x9d, 0x99, 0xa8, 0x07, 0x66, 0xf0, 0x1c, 0xf4, 0xc1, 0xcc, 0x4b, 0x7f, 0x35, 0xec,
	0x59, 0xff, 0x7a, 0xef, 0x77, 0xa1, 0xd4, 0xe6, 0xfc, 0x3b, 0xf3, 0x6e, 0x14, 0xc0, 0x61, 0x7e,
	0x3c, 0x5e, 0x6f, 0x26, 0xe8, 0x77, 0x33, 0x41, 0x4f, 0x2f, 0xdb, 0x1f, 0x82, 0x3e, 0x1b, 0x82,
	0xb7, 0x0d, 0xc1, 0xbb, 0x86, 0xe0, 0xef, 0x86, 0xe0, 0x8f, 0x96, 0xa0, 0x5d, 0x4b, 0xd0, 0x57,
	0x4b, 0xd0, 0xdb, 0x43, 0x2a, 0x61, 0x59, 0x71, 0x9a, 0xa8, 0x8c, 0xc9, 0x5c, 0x82, 0x8c, 0xef,
	0x56, 0x31, 0xd7, 0x6c, 0xdf, 0x6f, 0x3d, 0x65, 0xba, 0xe2, 0x99, 0x5a, 0x54, 0x2b, 0xd1, 0x55,
	0x62, 0x9b, 0xe6, 0x47, 0xf6, 0xa5, 0xf7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x48, 0xd5, 0xc1,
	0xdd, 0x87, 0x01, 0x00, 0x00,
}

func (m *TxWithResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxWithResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TxWithResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TxResponse != nil {
		{
			size, err := m.TxResponse.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Tx != nil {
		{
			size, err := m.Tx.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TxWithResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Tx != nil {
		l = m.Tx.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.TxResponse != nil {
		l = m.TxResponse.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TxWithResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxWithResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxWithResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tx == nil {
				m.Tx = &tx.Tx{}
			}
			if err := m.Tx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TxResponse == nil {
				m.TxResponse = &types.TxResponse{}
			}
			if err := m.TxResponse.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
